//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace bike_project_net_client.BikeSoapService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.bikeproject/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.bikeproject/")]
    public partial class bike : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brandField;
        
        private double priceField;
        
        private System.DateTime purchaseDateField;
        
        private bool purchaseDateFieldSpecified;
        
        private string serialField;
        
        private type typeField;
        
        private bool typeFieldSpecified;
        
        private double weightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime purchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
                this.RaisePropertyChanged("purchaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool purchaseDateSpecified {
            get {
                return this.purchaseDateFieldSpecified;
            }
            set {
                this.purchaseDateFieldSpecified = value;
                this.RaisePropertyChanged("purchaseDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public type type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.bikeproject/")]
    public enum type {
        
        /// <remarks/>
        ROAD,
        
        /// <remarks/>
        MOUNTAIN,
        
        /// <remarks/>
        GRAVEL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller.bikeproject/", ConfigurationName="BikeSoapService.BikeController")]
    public interface BikeController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/findBikeBySerialRequest", ReplyAction="http://controller.bikeproject/BikeController/findBikeBySerialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bike_project_net_client.BikeSoapService.findBikeBySerialResponse findBikeBySerial(bike_project_net_client.BikeSoapService.findBikeBySerialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/findBikeBySerialRequest", ReplyAction="http://controller.bikeproject/BikeController/findBikeBySerialResponse")]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.findBikeBySerialResponse> findBikeBySerialAsync(bike_project_net_client.BikeSoapService.findBikeBySerialRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/deleteBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/deleteBikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(bike_project_net_client.BikeSoapService.Exception), Action="http://controller.bikeproject/BikeController/deleteBike/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bike_project_net_client.BikeSoapService.deleteBikeResponse deleteBike(bike_project_net_client.BikeSoapService.deleteBikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/deleteBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/deleteBikeResponse")]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.deleteBikeResponse> deleteBikeAsync(bike_project_net_client.BikeSoapService.deleteBikeRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/saveBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/saveBikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(bike_project_net_client.BikeSoapService.Exception), Action="http://controller.bikeproject/BikeController/saveBike/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bike_project_net_client.BikeSoapService.saveBikeResponse saveBike(bike_project_net_client.BikeSoapService.saveBikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/saveBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/saveBikeResponse")]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.saveBikeResponse> saveBikeAsync(bike_project_net_client.BikeSoapService.saveBikeRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/updateBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/updateBikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(bike_project_net_client.BikeSoapService.Exception), Action="http://controller.bikeproject/BikeController/updateBike/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bike_project_net_client.BikeSoapService.updateBikeResponse updateBike(bike_project_net_client.BikeSoapService.updateBikeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/updateBikeRequest", ReplyAction="http://controller.bikeproject/BikeController/updateBikeResponse")]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.updateBikeResponse> updateBikeAsync(bike_project_net_client.BikeSoapService.updateBikeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/getBikesRequest", ReplyAction="http://controller.bikeproject/BikeController/getBikesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bike_project_net_client.BikeSoapService.getBikesResponse getBikes(bike_project_net_client.BikeSoapService.getBikesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.bikeproject/BikeController/getBikesRequest", ReplyAction="http://controller.bikeproject/BikeController/getBikesResponse")]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.getBikesResponse> getBikesAsync(bike_project_net_client.BikeSoapService.getBikesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBikeBySerial", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class findBikeBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findBikeBySerialRequest() {
        }
        
        public findBikeBySerialRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBikeBySerialResponse", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class findBikeBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bike_project_net_client.BikeSoapService.bike @return;
        
        public findBikeBySerialResponse() {
        }
        
        public findBikeBySerialResponse(bike_project_net_client.BikeSoapService.bike @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBike", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class deleteBikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteBikeRequest() {
        }
        
        public deleteBikeRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteBikeResponse", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class deleteBikeResponse {
        
        public deleteBikeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveBike", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class saveBikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bike_project_net_client.BikeSoapService.bike arg0;
        
        public saveBikeRequest() {
        }
        
        public saveBikeRequest(bike_project_net_client.BikeSoapService.bike arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveBikeResponse", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class saveBikeResponse {
        
        public saveBikeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBike", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class updateBikeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bike_project_net_client.BikeSoapService.bike arg0;
        
        public updateBikeRequest() {
        }
        
        public updateBikeRequest(bike_project_net_client.BikeSoapService.bike arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBikeResponse", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class updateBikeResponse {
        
        public updateBikeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBikes", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class getBikesRequest {
        
        public getBikesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBikesResponse", WrapperNamespace="http://controller.bikeproject/", IsWrapped=true)]
    public partial class getBikesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.bikeproject/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bike_project_net_client.BikeSoapService.bike[] @return;
        
        public getBikesResponse() {
        }
        
        public getBikesResponse(bike_project_net_client.BikeSoapService.bike[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BikeControllerChannel : bike_project_net_client.BikeSoapService.BikeController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeControllerClient : System.ServiceModel.ClientBase<bike_project_net_client.BikeSoapService.BikeController>, bike_project_net_client.BikeSoapService.BikeController {
        
        public BikeControllerClient() {
        }
        
        public BikeControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BikeControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bike_project_net_client.BikeSoapService.findBikeBySerialResponse bike_project_net_client.BikeSoapService.BikeController.findBikeBySerial(bike_project_net_client.BikeSoapService.findBikeBySerialRequest request) {
            return base.Channel.findBikeBySerial(request);
        }
        
        public bike_project_net_client.BikeSoapService.bike findBikeBySerial(string arg0) {
            bike_project_net_client.BikeSoapService.findBikeBySerialRequest inValue = new bike_project_net_client.BikeSoapService.findBikeBySerialRequest();
            inValue.arg0 = arg0;
            bike_project_net_client.BikeSoapService.findBikeBySerialResponse retVal = ((bike_project_net_client.BikeSoapService.BikeController)(this)).findBikeBySerial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.findBikeBySerialResponse> bike_project_net_client.BikeSoapService.BikeController.findBikeBySerialAsync(bike_project_net_client.BikeSoapService.findBikeBySerialRequest request) {
            return base.Channel.findBikeBySerialAsync(request);
        }
        
        public System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.findBikeBySerialResponse> findBikeBySerialAsync(string arg0) {
            bike_project_net_client.BikeSoapService.findBikeBySerialRequest inValue = new bike_project_net_client.BikeSoapService.findBikeBySerialRequest();
            inValue.arg0 = arg0;
            return ((bike_project_net_client.BikeSoapService.BikeController)(this)).findBikeBySerialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bike_project_net_client.BikeSoapService.deleteBikeResponse bike_project_net_client.BikeSoapService.BikeController.deleteBike(bike_project_net_client.BikeSoapService.deleteBikeRequest request) {
            return base.Channel.deleteBike(request);
        }
        
        public void deleteBike(string arg0) {
            bike_project_net_client.BikeSoapService.deleteBikeRequest inValue = new bike_project_net_client.BikeSoapService.deleteBikeRequest();
            inValue.arg0 = arg0;
            bike_project_net_client.BikeSoapService.deleteBikeResponse retVal = ((bike_project_net_client.BikeSoapService.BikeController)(this)).deleteBike(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.deleteBikeResponse> bike_project_net_client.BikeSoapService.BikeController.deleteBikeAsync(bike_project_net_client.BikeSoapService.deleteBikeRequest request) {
            return base.Channel.deleteBikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.deleteBikeResponse> deleteBikeAsync(string arg0) {
            bike_project_net_client.BikeSoapService.deleteBikeRequest inValue = new bike_project_net_client.BikeSoapService.deleteBikeRequest();
            inValue.arg0 = arg0;
            return ((bike_project_net_client.BikeSoapService.BikeController)(this)).deleteBikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bike_project_net_client.BikeSoapService.saveBikeResponse bike_project_net_client.BikeSoapService.BikeController.saveBike(bike_project_net_client.BikeSoapService.saveBikeRequest request) {
            return base.Channel.saveBike(request);
        }
        
        public void saveBike(bike_project_net_client.BikeSoapService.bike arg0) {
            bike_project_net_client.BikeSoapService.saveBikeRequest inValue = new bike_project_net_client.BikeSoapService.saveBikeRequest();
            inValue.arg0 = arg0;
            bike_project_net_client.BikeSoapService.saveBikeResponse retVal = ((bike_project_net_client.BikeSoapService.BikeController)(this)).saveBike(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.saveBikeResponse> bike_project_net_client.BikeSoapService.BikeController.saveBikeAsync(bike_project_net_client.BikeSoapService.saveBikeRequest request) {
            return base.Channel.saveBikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.saveBikeResponse> saveBikeAsync(bike_project_net_client.BikeSoapService.bike arg0) {
            bike_project_net_client.BikeSoapService.saveBikeRequest inValue = new bike_project_net_client.BikeSoapService.saveBikeRequest();
            inValue.arg0 = arg0;
            return ((bike_project_net_client.BikeSoapService.BikeController)(this)).saveBikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bike_project_net_client.BikeSoapService.updateBikeResponse bike_project_net_client.BikeSoapService.BikeController.updateBike(bike_project_net_client.BikeSoapService.updateBikeRequest request) {
            return base.Channel.updateBike(request);
        }
        
        public void updateBike(bike_project_net_client.BikeSoapService.bike arg0) {
            bike_project_net_client.BikeSoapService.updateBikeRequest inValue = new bike_project_net_client.BikeSoapService.updateBikeRequest();
            inValue.arg0 = arg0;
            bike_project_net_client.BikeSoapService.updateBikeResponse retVal = ((bike_project_net_client.BikeSoapService.BikeController)(this)).updateBike(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.updateBikeResponse> bike_project_net_client.BikeSoapService.BikeController.updateBikeAsync(bike_project_net_client.BikeSoapService.updateBikeRequest request) {
            return base.Channel.updateBikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.updateBikeResponse> updateBikeAsync(bike_project_net_client.BikeSoapService.bike arg0) {
            bike_project_net_client.BikeSoapService.updateBikeRequest inValue = new bike_project_net_client.BikeSoapService.updateBikeRequest();
            inValue.arg0 = arg0;
            return ((bike_project_net_client.BikeSoapService.BikeController)(this)).updateBikeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bike_project_net_client.BikeSoapService.getBikesResponse bike_project_net_client.BikeSoapService.BikeController.getBikes(bike_project_net_client.BikeSoapService.getBikesRequest request) {
            return base.Channel.getBikes(request);
        }
        
        public bike_project_net_client.BikeSoapService.bike[] getBikes() {
            bike_project_net_client.BikeSoapService.getBikesRequest inValue = new bike_project_net_client.BikeSoapService.getBikesRequest();
            bike_project_net_client.BikeSoapService.getBikesResponse retVal = ((bike_project_net_client.BikeSoapService.BikeController)(this)).getBikes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.getBikesResponse> bike_project_net_client.BikeSoapService.BikeController.getBikesAsync(bike_project_net_client.BikeSoapService.getBikesRequest request) {
            return base.Channel.getBikesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bike_project_net_client.BikeSoapService.getBikesResponse> getBikesAsync() {
            bike_project_net_client.BikeSoapService.getBikesRequest inValue = new bike_project_net_client.BikeSoapService.getBikesRequest();
            return ((bike_project_net_client.BikeSoapService.BikeController)(this)).getBikesAsync(inValue);
        }
    }
}
