package bikeproject.model;

import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;

// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class BikeServiceClient {
    public static final BikeService BIKE_SERVICE = new Bike_Service().getBikerservice();
    public final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-mm-dd");
    public final static DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
}
